map_size = [10, 10]

[train]
turn_speed = 2.0
rail_speed = 5.0
offrail_speed = 3.0
acceleration = 1.0
deceleration = 2.0
wagon_size = [0.9, 0.45]
wagon_spacing = 0.1

[resources.Coal]
value = 5
rarity = 1

[resources.PlusCent]
value = 0
rarity = 5
