map_size = [15.0, 15.0]
depo_size = [1.6, 3.2]

[train]
wagon_spacing = 0.1
turn_speed = 2.0
overtime_slowdown = 0.3
speed = 5.0
acceleration = 1.0
deceleration = 2.0

[[train.starter_wagons]]
size = [0.9, 0.45]
max_health = 10.0

[[train.starter_wagons]]
size = [0.9, 0.45]
max_health = 10.0
[train.starter_wagons.collect]
resource = "Food"
range = 2.5
speed = 1.0
capacity = 15

[resource]
spawn_time = 1.0

[resources.Wood]
value = 0.5
amount = 30
speed = 2.0
per_collection = 10

[resources.Coal]
value = 0.75
amount = 20
speed = 1.6
per_collection = 4

[resources.Food]
value = 1.0
amount = 30
speed = 2.0
per_collection = 1
